In [1]:
import pandas as pd
import numpy as np

In [3]:
dengu_spatial = pd.read_csv("../datasets/dengu_spatial.csv")
dengu_temporal = pd.read_csv("../datasets/dengu_temporal.csv")

print(f"Length of Spatial Data: {len(dengu_spatial)}")
print("------------------------------------")
print("Spatial Data Described: ")
display(dengu_spatial.describe())
print("------------------------------------")
print("Spatial Data Null Vals")
display(dengu_spatial.isnull().sum())

print("\n------------------------------------\n------------------------------------\n")

print(f"Length of Spatial Data: {len(dengu_spatial)}")
print("------------------------------------")
print("Temporal Data Described: ")
display(dengu_temporal.describe())
print("------------------------------------")
print("Temporal Data Null Vals")
display(dengu_temporal.isnull().sum())

Length of Spatial Data: 2933
------------------------------------
Spatial Data Described:

       FAO_GAUL_code  IBGE_code         Year  dengue_total
count    2933.000000        0.0  2933.000000   2933.000000
mean    21419.323219        NaN  2022.753495     94.727924
std      4464.287623        NaN     1.503381   1447.455580
min       175.000000        NaN  2005.000000      0.000000
25%     22352.000000        NaN  2022.000000      0.000000
50%     22357.000000        NaN  2023.000000      2.000000
75%     22363.000000        NaN  2024.000000     13.000000
max     22364.000000        NaN  2025.000000  54784.000000

------------------------------------
Spatial Data Null Vals

adm_0_name                         0
adm_1_name                       154
adm_2_name                       131
full_name                          0
ISO_A0                             0
FAO_GAUL_code                      0
RNE_iso_code                       0
IBGE_code                       2933
calendar_start_date                0
calendar_end_date                  0
Year                               0
dengue_total                       0
case_definition_standardised       0
S_res                              0
T_res                              0
UUID                               0
region                             0
dtype: int64

------------------------------------
------------------------------------

Length of Spatial Data: 2933
------------------------------------
Temporal Data Described:

       FAO_GAUL_code  IBGE_code         Year  dengue_total
count    2963.000000        0.0  2963.000000   2963.000000
mean    21204.227135        NaN  2022.760715     93.370570
std      4924.717253        NaN     1.494684    718.547273
min       175.000000        NaN  2005.000000      0.000000
25%     22352.000000        NaN  2022.000000      0.000000
50%     22357.000000        NaN  2023.000000      2.000000
75%     22363.000000        NaN  2024.000000     14.000000
max     22364.000000        NaN  2025.000000  14534.000000

------------------------------------
Temporal Data Null Vals

adm_0_name                         0
adm_1_name                       184
adm_2_name                       161
full_name                          0
ISO_A0                             0
FAO_GAUL_code                      0
RNE_iso_code                       0
IBGE_code                       2963
calendar_start_date                0
calendar_end_date                  0
Year                               0
dengue_total                       0
case_definition_standardised       0
S_res                              0
T_res                              0
UUID                               0
region                             0
dtype: int64