importing modules

In [1]:
import pandas as pd
import numpy as np

Basic Describe and Null Check of both dataset

In [2]:
district = pd.read_csv("../datasets/nepal_district_centroids.csv")
dengu_temporal = pd.read_csv("../datasets/dengu_temporal.csv")

print(f"Length of District Data: {len(district)}")
print("------------------------------------")
print("District Data Described: ")
display(district.describe())
print("------------------------------------")
print("District Data Null Vals")
display(district.isnull().sum())

print("\n------------------------------------\n------------------------------------\n")

print(f"Length of Temporal Data: {len(dengu_temporal)}")
print("------------------------------------")
print("Temporal Data Described: ")
display(dengu_temporal.describe())
print("------------------------------------")
print("Temporal Data Null Vals")
display(dengu_temporal.isnull().sum())

Length of District Data: 77
------------------------------------
District Data Described:

       LONGITUDE   LATITUDE
count  77.000000  77.000000
mean   84.231803  28.013663
std     2.161370   0.878358
min    80.324299  26.579753
25%    82.420482  27.331392
50%    84.227051  27.918388
75%    85.946616  28.672759
max    87.916711  30.031208

------------------------------------
District Data Null Vals

DISTRICT     0
LONGITUDE    0
LATITUDE     0
dtype: int64

------------------------------------
------------------------------------

Length of Temporal Data: 2963
------------------------------------
Temporal Data Described:

       FAO_GAUL_code  IBGE_code         Year  dengue_total
count    2963.000000        0.0  2963.000000   2963.000000
mean    21204.227135        NaN  2022.760715     93.370570
std      4924.717253        NaN     1.494684    718.547273
min       175.000000        NaN  2005.000000      0.000000
25%     22352.000000        NaN  2022.000000      0.000000
50%     22357.000000        NaN  2023.000000      2.000000
75%     22363.000000        NaN  2024.000000     14.000000
max     22364.000000        NaN  2025.000000  14534.000000

------------------------------------
Temporal Data Null Vals

adm_0_name                         0
adm_1_name                       184
adm_2_name                       161
full_name                          0
ISO_A0                             0
FAO_GAUL_code                      0
RNE_iso_code                       0
IBGE_code                       2963
calendar_start_date                0
calendar_end_date                  0
Year                               0
dengue_total                       0
case_definition_standardised       0
S_res                              0
T_res                              0
UUID                               0
region                             0
dtype: int64

In [3]:
print("Temporal Data")
display(dengu_temporal.dtypes)

Temporal Data

adm_0_name                          str
adm_1_name                          str
adm_2_name                          str
full_name                           str
ISO_A0                              str
FAO_GAUL_code                     int64
RNE_iso_code                        str
IBGE_code                       float64
calendar_start_date                 str
calendar_end_date                   str
Year                              int64
dengue_total                      int64
case_definition_standardised        str
S_res                               str
T_res                               str
UUID                                str
region                              str
dtype: object

In [4]:
# Print first 5 data of temporal
print('Temporal Data structure')
dengu_temporal.head()

Temporal Data structure

,adm_0_name,adm_1_name,adm_2_name,full_name,ISO_A0,FAO_GAUL_code,RNE_iso_code,IBGE_code,calendar_start_date,calendar_end_date,Year,dengue_total,case_definition_standardised,S_res,T_res,UUID,region
0,NEPAL,NaN,SYANGJA,"NEPAL, SYANGJA",NPL,22364,NPL,NaN,2016-01-01,2016-12-31,2016,1,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO
1,NEPAL,NaN,DHADING,"NEPAL, DHADING",NPL,22353,NPL,NaN,2016-01-01,2016-12-31,2016,4,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO
2,NEPAL,NaN,BARA,"NEPAL, BARA",NPL,22353,NPL,NaN,2016-01-01,2016-12-31,2016,4,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO
3,NEPAL,NaN,DANG,"NEPAL, DANG",NPL,22360,NPL,NaN,2016-01-01,2016-12-31,2016,8,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO
4,NEPAL,NaN,RUKUM,"NEPAL, RUKUM",NPL,22360,NPL,NaN,2016-01-01,2016-12-31,2016,1,Total,Admin1,Year,MOH-NPL-2016-Y01-00,SEARO

Show Different value counts in the Temporal Data

In [5]:
display(dengu_temporal["case_definition_standardised"].value_counts())
display(dengu_temporal["T_res"].value_counts())

case_definition_standardised
Total        2953
Confirmed      10
Name: count, dtype: int64

T_res
Month    2873
Year       49
Week       41
Name: count, dtype: int64

In [6]:
# remove Yearly and weekly dataset as they carry 3% only data in whole dataset
dengu_temporal = dengu_temporal[(dengu_temporal["T_res"]!="Year") & (dengu_temporal["T_res"]!="Week")]

Add new Location Column and remove unnecessary

In [7]:
# Location In Dataset is Added 
dengu_temporal["Location"] = dengu_temporal["adm_2_name"].fillna(dengu_temporal["full_name"].str.split(",").str[-1])

# Remove unnecessary Columns
dengu_temporal = dengu_temporal.drop(
    columns="adm_0_name,adm_1_name,adm_2_name,full_name,ISO_A0,FAO_GAUL_code,RNE_iso_code,IBGE_code,S_res,region,UUID,case_definition_standardised,T_res".split(",")
)

dengu_temporal[:10]

   calendar_start_date calendar_end_date  Year  dengue_total Location
27          2018-05-01        2018-05-31  2018             1    NEPAL
28          2018-06-01        2018-06-30  2018             7    NEPAL
29          2018-07-01        2018-07-31  2018            15    NEPAL
30          2018-08-01        2018-08-31  2018            34    NEPAL
31          2018-09-01        2018-09-30  2018            30    NEPAL
32          2018-10-01        2018-10-31  2018            21    NEPAL
48          2016-09-01        2016-09-30  2016             2    NEPAL
49          2016-11-01        2016-11-30  2016           442    NEPAL
50          2016-12-01        2016-12-31  2016            10    NEPAL
51          2017-01-01        2017-01-31  2017             3    NEPAL

Extract month using start date. Then delete other unnecessary dates

In [8]:
# convert to date time format
dengu_temporal["calendar_start_date"] = pd.to_datetime(dengu_temporal["calendar_start_date"])

#month map
month_map = {
    1: "Jan", 2: "Feb", 3: "Mar", 4: "Apr", 
    5: "May", 6: "Jun", 7: "Jul", 8: "Aug", 
    9: "Sep", 10: "Oct", 11: "Nov", 12: "Dec"
}

dengu_temporal["Month"] = dengu_temporal["calendar_start_date"].dt.month.map(month_map)
dengu_temporal.head()

   calendar_start_date calendar_end_date  Year  dengue_total Location Month
27          2018-05-01        2018-05-31  2018             1    NEPAL   May
28          2018-06-01        2018-06-30  2018             7    NEPAL   Jun
29          2018-07-01        2018-07-31  2018            15    NEPAL   Jul
30          2018-08-01        2018-08-31  2018            34    NEPAL   Aug
31          2018-09-01        2018-09-30  2018            30    NEPAL   Sep

In [9]:
# show all location counts
display(dengu_temporal["Location"].value_counts())
print(f'Total Length = {len(dengu_temporal)}')
dengu_temporal.head()

Location
NEPAL           101
ACHHAM           36
ARGHAKHANCHI     36
BAGLUNG          36
BAITADI          36
               ...
SYANGJA          36
TANAHU           36
TAPLEJUNG        36
TERHATHUM        36
UDAYAPUR         36
Name: count, Length: 78, dtype: int64

Total Length = 2873

   calendar_start_date calendar_end_date  Year  dengue_total Location Month
27          2018-05-01        2018-05-31  2018             1    NEPAL   May
28          2018-06-01        2018-06-30  2018             7    NEPAL   Jun
29          2018-07-01        2018-07-31  2018            15    NEPAL   Jul
30          2018-08-01        2018-08-31  2018            34    NEPAL   Aug
31          2018-09-01        2018-09-30  2018            30    NEPAL   Sep

The Location Nepal can give specific location and it only contains 3.5% of total dataset we delete rows

In [10]:
dengu_temporal = dengu_temporal[dengu_temporal["Location"]!="NEPAL"]
dengu_temporal.head()

,calendar_start_date,calendar_end_date,Year,dengue_total,Location,Month
110,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan
111,2022-01-01,2022-01-31,2022,0,ARGHAKHANCHI,Jan
112,2022-01-01,2022-01-31,2022,0,BAGLUNG,Jan
113,2022-01-01,2022-01-31,2022,0,BAITADI,Jan
114,2022-01-01,2022-01-31,2022,1,BAJHANG,Jan

Merge latitude and longitude data to dengu data

In [11]:
merged_df = pd.merge(dengu_temporal, district, left_on="Location", right_on="DISTRICT", how="left")

print(f"Length of Merged df = {len(merged_df)}")
merged_df.head()

Length of Merged df = 2772

,calendar_start_date,calendar_end_date,Year,dengue_total,Location,Month,DISTRICT,LONGITUDE,LATITUDE
0,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,ACHHAM,81.299520,29.113168
1,2022-01-01,2022-01-31,2022,0,ARGHAKHANCHI,Jan,ARGHAKHANCHI,83.076443,27.918388
2,2022-01-01,2022-01-31,2022,0,BAGLUNG,Jan,BAGLUNG,83.256547,28.345703
3,2022-01-01,2022-01-31,2022,0,BAITADI,Jan,BAITADI,80.571334,29.505689
4,2022-01-01,2022-01-31,2022,1,BAJHANG,Jan,BAJHANG,81.180034,29.707134

In [12]:
merged_df.drop(columns=["DISTRICT"], inplace=True)
merged_df.head()

,calendar_start_date,calendar_end_date,Year,dengue_total,Location,Month,LONGITUDE,LATITUDE
0,2022-01-01,2022-01-31,2022,0,ACHHAM,Jan,81.299520,29.113168
1,2022-01-01,2022-01-31,2022,0,ARGHAKHANCHI,Jan,83.076443,27.918388
2,2022-01-01,2022-01-31,2022,0,BAGLUNG,Jan,83.256547,28.345703
3,2022-01-01,2022-01-31,2022,0,BAITADI,Jan,80.571334,29.505689
4,2022-01-01,2022-01-31,2022,1,BAJHANG,Jan,81.180034,29.707134

In [13]:
merged_df.to_csv("../datasets/merged_data.csv", index=False)